name: Update Cydia Repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dpkg-dev
      run: sudo apt-get update && sudo apt-get install -y dpkg-dev bzip2

    - name: Generate Repository Files
      run: |
        dpkg-scanpackages -m debs /dev/null > Packages
        sed -i 's/Section: !CydiaVn-Tools/Section: Tools/g' Packages
        sed -i 's/Section: !GSMVN-Tools/Section: Tools/g' Packages
        sed -i 's/Section: !GSMVN-Themes/Section: Themes/g' Packages
        sed -i 's/Section: !CydiaVn-Apps/Section: Apps/g' Packages
        bzip2 -fk Packages

        echo "Origin: kazexyz's repo" > Release
        echo "Label: kazexyz's repo" >> Release
        echo "Suite: stable" >> Release
        echo "Version: 1.0" >> Release
        echo "Codename: kazexyz" >> Release
        echo "Architectures: iphoneos-arm" >> Release
        echo "Components: main" >> Release
        echo "Description: Personal archive for old iOS jailbreak tweaks." >> Release

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add Packages Packages.bz2 Release
        git commit -m "Auto-update repo files [skip ci]" || exit 0
        git push